# Generated by Django 2.1.7 on 2019-03-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notiID', models.IntegerField(primary_key=True, serialize=False)),
                ('notiTime', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('parkID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParkInfo',
            fields=[
                ('infoID', models.IntegerField(primary_key=True, serialize=False)),
                ('parkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.Park')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('positionID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('isOwner', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='parkinfo',
            name='positionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.Position'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.User'),
        ),
    ]
