# Generated by Django 2.1.7 on 2019-03-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='parkID',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='positionID',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
