# Generated by Django 2.1.7 on 2019-03-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_auto_20190321_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='positionID',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
