# Generated by Django 2.1.7 on 2019-03-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_parkinfo_isbusy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isOwner',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
