# Generated by Django 2.1.7 on 2019-03-22 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0007_auto_20190321_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(max_length=10)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.User')),
            ],
        ),
        migrations.CreateModel(
            name='PositionBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.ParkInfo')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.User')),
            ],
        ),
    ]
