# Generated by Django 2.1.7 on 2019-03-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0009_auto_20190322_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payMonth',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='payState',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
