# Generated by Django 2.1.7 on 2019-03-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0012_parkinfo_carid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinfo',
            name='isBind',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
