# Generated by Django 2.1.7 on 2019-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0014_user_oncepark'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinfo',
            name='minute',
            field=models.IntegerField(default=0),
        ),
    ]
